# Generated by Django 5.2.13 on 2026-04-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubboard', '0003_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='clubName',
            new_name='title',
        ),
    ]
