# Generated by Django 5.2.13 on 2026-04-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubboard', '0004_rename_author_club_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
